In [3]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5],
                        [-3, 2.4, 5],
                        [0.5, -2, -5.5],
                        [4, 2.3, -5.8]])

sample_data


array([[ 2.1, -1.9,  5.5],
       [-3. ,  2.4,  5. ],
       [ 0.5, -2. , -5.5],
       [ 4. ,  2.3, -5.8]])

In [2]:
sample_data.shape

(4, 3)

# 1. Binarisation

In [4]:
# binary data
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 1., 0.]])

# 2. Scaling

In [5]:
# smallest = 0 , highest = 1
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.72857143, 0.02272727, 1.        ],
       [0.        , 1.        , 0.95575221],
       [0.5       , 0.        , 0.02654867],
       [1.        , 0.97727273, 0.        ]])

In [6]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.72857143, 0.02272727, 1.        ],
       [0.        , 1.        , 0.95575221],
       [0.5       , 0.        , 0.02654867],
       [1.        , 0.97727273, 0.        ]])

# 3. L1 Normalisation: Least Absolute Deviation

In [7]:
l1_normalization = preprocessing.normalize(sample_data, norm='l1')
l1_normalization

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.28846154,  0.23076923,  0.48076923],
       [ 0.0625    , -0.25      , -0.6875    ],
       [ 0.33057851,  0.19008264, -0.47933884]])

# 4. L2 Normalizartion: Least Squares

In [8]:
l2_normalization = preprocessing.normalize(sample_data, norm='l2')
l2_normalization

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.47577111,  0.38061689,  0.79295185],
       [ 0.08512565, -0.34050261, -0.93638218],
       [ 0.53970345,  0.31032948, -0.78257   ]])