# Sample Data

In [1]:
import pandas as pd

census = {'height' : [158, 170, 183, 191, 155, 163, 180, 158, 170],
          'weight' : [64, 86, 84, 80, 49, 59, 67, 54, 67],
          'Gender' : ['Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female']
         }

census_df = pd.DataFrame(census)
census_df

height  weight  Gender
0     158      64    Male
1     170      86    Male
2     183      84    Male
3     191      80    Male
4     155      49  Female
5     163      59  Female
6     180      67  Female
7     158      54  Female
8     170      67  Female

In [2]:
import numpy as np 
train_x = np.array(census_df[['height', 'Gender']])
train_y = np.array(census_df['weight'])

In [3]:
train_x_transposed = np.transpose(train_x)

from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

binary = lb.fit_transform(train_x_transposed[1])
binary = binary.flatten()
binary

train_x_transposed[1] = binary
train_x_new = np.transpose(train_x_transposed)
train_x_new

array([[158, 1],
       [170, 1],
       [183, 1],
       [191, 1],
       [155, 0],
       [163, 0],
       [180, 0],
       [158, 0],
       [170, 0]], dtype=object)

In [4]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(n_neighbors=3)
model.fit(train_x_new, train_y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

In [5]:
height_q = 155
gender_q = 1
test_x = np.array([[height_q, gender_q]])

y_pred = model.predict(test_x)
y_pred

array([55.66666667])

# Evaluation of KNN

In [6]:
X_test = np.array([[168, 1], [180, 1], [160, 0], [169, 0]])
y_test = np.array([65, 96, 52, 67])

y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

# R-squared

In [7]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)
r_squared

0.6290565226735438

# MAE

In [8]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)
MAE

8.333333333333336

# MSE

In [9]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)
MSE

95.8888888888889

# Standard Scaler

In [10]:
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import euclidean

ss= StandardScaler()

In [11]:
#Height in cm
X_train = np.array([[1700,0],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)

X_new = np.array([1640, 0])
X_new_scaled = ss.transform(X_train)

distance = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print(f"distance = {distance}")

distance = [0.0, 2.8284271247461903]


In [12]:
# Height in meter
X_train = np.array([[1.7,0],[1.6,1]])
X_train_scaled = ss.fit_transform(X_train)

X_new = np.array([1.64, 0])
X_new_scaled = ss.transform(X_train)

distance = [euclidean(X_new_scaled[0], d) for d in X_train_scaled]
print(f"distance = {distance}")

distance = [0.0, 2.8284271247461903]
